version: '3.8'

# The Payload CMS application along with MongoDB. Run `docker compose up -d`
# to start both containers.
services:
  payload:
    build: .
    working_dir: /app
    volumes:
      # Mount the application code and uploads directory so changes persist
      - ./payload:/app/payload
      - ./uploads:/uploads
    environment:
      - PAYLOAD_CONFIG_PATH=/app/payload/payload.config.js
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - MONGODB_URI=${MONGODB_URI}
      - UPLOAD_DIR=${UPLOAD_DIR}
      - PORT=${PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERVER_URL=${SERVER_URL}
    ports:
      - "3000:3000"
    command: sh -c "node /app/payload/server.js"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    volumes:
      # Persist MongoDB data on the host so containers can be recreated
      - ./db:/data/db
    restart: unless-stopped

volumes:
  uploads:
  db:
